<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>coug_mapviz</name>
  <version>0.0.0</version>
  <description>MapViz visualization configurations and plugins.</description>
  <maintainer email="snelsond@byu.edu">snelsondurrant</maintainer>
  <license>Apache-2.0</license>
  <url type="repository">https://github.com/cougars-auv/coug_mapviz</url>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <exec_depend>python3-yaml</exec_depend>

  <depend>coug_interfaces</depend>
  <depend>geographic_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>libqt5-core</depend>
  <depend>libqt5-gui</depend>
  <depend>libqt5-opengl</depend>
  <depend>libqt5-opengl-dev</depend>
  <depend>libqt5-widgets</depend>
  <depend>mapviz</depend>
  <depend>mapviz_plugins</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>std_srvs</depend>
  <depend>swri_transform_util</depend>
  <depend>tf2</depend>
  <depend>tile_map</depend>
  <depend>yaml-cpp</depend>

  <test_depend>ament_cmake_gtest</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
    <mapviz plugin="${prefix}/mapviz_plugins.xml" />
  </export>

</package>
